### ISSUE TITLE
Brainstorming how to structure this

### ISSUE THREAD

**Issue by danielballan** [bluesky/tiled-example-database#1]
Recapping and continuing a conversation with @Kezzsim here in public so that other (@dylanmcreynolds especially) may follow along and weigh in if they like.

<hr />

The first pass, as sketched in this repo, derives from a postgres image

https://github.com/bluesky/tiled-example-database/blob/e53fa2ff2bff494a246559396d2e47b3f47ec3bf/postgres/Dockerfile#L2

and goes on to install Python and Tiled into that image, and then generate example data. This approach has a couple downsides.

First, the image size will grow significantly, as it now carries:

1. Postgres
2. Python, Tiled, and Tiled's dependencies
3. The generated data

Ideally, our test image should need to carry the weight of only (1) and (3)[^1]. Second, we already have a tiled image, and it would be nice if we could just use that rather than having a second version of that logic here. Third, it just feels "off" to me to run Python from inside the postgres container. The postgres container should run postgres, and we should connect to postgres from _outside_ the container if we want to do things with it from Python.

There are lots of example of using `/docker-entrypoint-initdb.d/` to generate example data within the postgres container, but these examples tend to introduce no other dependencies. They are running bash and SQL code directly, not installing Python and its HTTP stack. I think that distinction is what makes our requirements unusual.

Here is another approach to consider and perhaps iterate on. In a GHA workflow:

1. Run a Postgres image (nothing custom, just a standard image). Mount a directory in the host's storage that we can use to ex-filtrate data.
2. Run the Tiled image, overriding its `CMD` to execute a Python script, which in turn takes a `DATABASE_URI` as a commandline argument. Example: `docker ghcr.io/bluesky/tiled:latest python generate_data.py DATABASE_URI`
3. `docker exec` in the postgres container to dump a `data.sql` file to the host's storage.
4. Stop the Postgres and Tiled images; we are done with them.
5. Build a new image, derived from `postgres`. In the `Dockerfile`, `COPY` that `data.sql` file from the host into the image. Perhaps use the `/docker-entrypoint-initdb.d/` machinery to execute it, as needed.

In summary, this repo would contain:
* `generate_data.py`
* a `Dockerfile` that presumes `data.sql` exists on the host's storage
* a GHA workflow that stiches it all together, first using `postgres` and `tiled` to create `data.sql`, and then building a custom `postgres` image that layers in the data

The script `generate_data.py` would look something like:

```py
#!/usr/env/bin python

# Usage: generate_sample_data.py DATABASE_URI

import sys
from tiled.catalog import from_uri
from tiled.client import Context, from_context
from tiled.server.app import build_app

uri = sys.argv[1]
catalog = from_uri(uri)
with Context.from_app(build_app(catalog)) as context:
    client = from_context(context)
    # Write data
```

[^1]: This is a great primer on how to understand and interrogate container image size. https://www.youtube.com/watch?v=kx-SeGbkNPU

**Comment by dylanmcreynolds** [comment]
I haven't thought too deeply about this, but I'm not a huge fan of combining tiled and postgres into a single image in order to get these features.

Jus to be clear, in examples like [these](https://medium.com/@asuarezaceves/initializing-a-postgresql-database-with-a-dataset-using-docker-compose-a-step-by-step-guide-3feebd5b1545) the `*.sql` file carries both database definition and the loading of data. In our case, we don't need database definition at all, because SQLAlchemy handles creation of relational database bits, right?

**Comment by Kezzsim** [comment]
I think that's correct, hypothetically we *could* get the exact SQL commands that Tiled is running from it's ORM / `EXPLAIN` and then just put that in a `.sql` file but I'm not sure how kosher that would be with @danielballan .

I have an ideal workflow on my local machine right now because what we need is actually rather simple:
1) Pull a fresh Postgres docker image
2) Run the Postgres docker image, connect Tiled to it and generate the data
3) Stop the container
4) Use Docker `commit` and `docker image push` to take the image with the data and push it onto the container repository

The thing we're trying to come up with is a way to make this tenable to C.I. or something we can write in a `Dockerfile` / `docker-compose`

**Comment by danielballan** [comment]
> I'm not a huge fan of combining tiled and postgres into a single image in order to get these features.

Yes, I think all three of us are on the same page about this---initial draft notwithstanding.

I think it makes sense to start with exactly what you proposed above, @Kezzsim. Let's start by simply running those steps in a GHA workflow.

In the future we can consider a solution like the one I outlined above (`Dockerfile` instead of `docker commit`...) but I think what you described will work just fine on CI. In both solutions, we're keeping postgres and Python/Tiled in separate images.

**Comment by prjemian** [comment]
Perhaps you want separate, interacting containers?

**Comment by danielballan** [comment]
Yes, I think that's exactly where we are landing. Our existing Tiled container interacts with a standard Postgres container, we save the resulting state of the Postgres container as a Postgres+Data image.

**Comment by danielballan** [comment]
Documenting how this plan has evolved, and simplified, in conversations between @Kezzsim and me:

- Use standard Postgres container and Tiled container to export a `.sql` file containing SQL commands for building an example database in Postgres.
- Use the Tiled container to export a SQLite file containing the example data.
- Publish these files together as artifacts attached to a GitHub Release.
- When running Tiled tests locally or on CI, obtain these artifacts, load the `.sql` file into Postgres using standard mechanisms, and make them available to the test runner. (The test runner, for its part, will skip tests that have these external dependencies if the external dependencies are not available.)

**Comment by danielballan** [comment]
I am pleased with where this landed.

A Python script uses the Tiled client to generate example data against (1) a running vanilla PG container and (2) SQLite. It publishes the pgdump-ed output of (1) and the SQLite file from (2) in a GH release. These can be downloaded and used for local or CI tests. https://github.com/bluesky/tiled-example-database/releases/tag/0.0.21
